version: '3.8'

services:
  flask_app:
    build: .
    restart: always
    ports:
      - '4200:4200'
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - database_network
      - nginx_network
  database:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=robot
      - POSTGRES_PASSWORD=robot
      - POSTGRES_DB=robot
    networks:
      - database_network
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    networks:
      - nginx_network
    depends_on:
      - flask_app

networks:
  database_network:
    name: database_network
    driver: bridge
  nginx_network:
    name: nginx_network
    driver: bridge

volumes:
  postgres_data:
